version: '2'
services:
  mysql:
    image: 'mysql:5.7.13'
    environment:
      - MYSQL_ROOT_PASSWORD=Abcd1234
      - >-
        occs:description=The official MySQL image. Please update the password
        before you use this in production use cases. This example is provided
        as-is for educational purposes and should not be used in production.
  wlsadmin:
    image: 'ericgmader/c18lvdemo:0.1'
    environment:
      - ADMIN_PASSWORD=Abcd1234
      - DOMAIN_NAME=c18lv_domain
      - ADMIN_PORT=7001
      - ADMIN_HOST=wlsadmin
      - CLUSTER_NAME=DockerCluster
      - PRODUCTION_MODE=dev
      - ADMIN_USERNAME=weblogic
      - ADMIN_NAME=AdminServer
      - MS_PORT=8001
      - DEBUG_FLAG=false
      - 'occs:description=WebLogic Admin Server'
    ports:
      - '7001:7001/tcp'
    volumes:
      - 'domain_data:/u01/oracle/user_projects'
    links:
      - mysql
  wlsms:
    image: 'ericgmader/c18lvdemo:0.1'
    command: createServer.sh
    environment:
      - ADMIN_PASSWORD=Abcd1234
      - DOMAIN_NAME=c18lv_domain
      - ADMIN_PORT=7001
      - ADMIN_HOST=wlsadmin
      - CLUSTER_NAME=DockerCluster
      - PRODUCTION_MODE=dev
      - ADMIN_USERNAME=weblogic
      - ADMIN_NAME=AdminServer
      - MS_NAME=MS1
      - MS_PORT=8001
      - DEBUG_FLAG=false
      - 'occs:description=WebLogic Managed Server'
    ports:
      - '8001:8001/tcp'
    volumes:
      - 'domain_data:/u01/oracle/user_projects'
    links:
      - wlsadmin

volumes:
  domain_data:
  mysql_data:
